- hosts: all
  connection: local
  become: no


  vars_prompt:
  - name: "vsphere_username"
    prompt: "Enter your vsphere username"
    private: yes
  - name: "vsphere_password"
    prompt: "Enter your vsphere password"
    private: yes
      
  vars:
    esxi_hostname: "{{ hostvars[inventory_hostname]['esxi_host'] }}"
    esxi_ip: "{{ hostvars[inventory_hostname]['esxi_ip'] }}"
    vsphere_datacenter: ha-datacenter
    vsphere_datastore: "{{ hostvars[inventory_hostname]['datastore'] }}"
    vsphere_iso_datastore: QNAPDataStore
    vsphere_iso_directory: ISOs
    vsphere_hostname: vcsa.lab.clearfocustech.com
    vsphere_hostname: "{{ esxi_ip }}"
    vm_network: "{{ hostvars[inventory_hostname]['vm_network'] }}"
    iso_image: "{{ hostvars[inventory_hostname]['iso_image'] }}"
    ram_mb: "{{ hostvars[inventory_hostname]['ram_mb'] }}"
    cpu_count: "{{ hostvars[inventory_hostname]['cpu_count'] }}"
    disk_gb: "{{ hostvars[inventory_hostname]['disk_gb'] }}"
    unattend: "{{ hostvars[inventory_hostname]['unattend'] }}"
    iso_requires_keypress: "{{ hostvars[inventory_hostname]['iso_requires_keypress'] }}" # Some Windows ISO install images require a key press to boot the install, if set to true, this will try and rebuild the ISO to skip that. 
 
  tasks:
 
  - command: mktemp -d
    delegate_to: localhost
    register: tempdir
 
  - name: ensure local build directory exists
    file: 
      path: build
      state: directory

  - name: Query if Windows ISO already exists, do not constantly re-upload it.
    vsphere_file:
      host: "{{ vsphere_hostname }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      datacenter: "{{ vsphere_datacenter }}"
      datastore: "{{ vsphere_iso_datastore }}"
      path: "{{ vsphere_iso_directory }}/{{ iso_image }}"
      state: file
      validate_certs: False
    delegate_to: localhost
    register: iso_exists
    ignore_errors: true

  - name: place autounattend.xml file on custom iso image
    template:
      src: "{{ playbook_dir }}/templates/{{ unattend }}.j2"
      dest: "{{ tempdir.stdout }}/autounattend.xml"
 
  - name: place ip-hostname.ps1 on custom iso image
    template:
      src: "{{ playbook_dir }}/templates/ip-hostname.ps1.j2"
      dest: "{{ tempdir.stdout }}/ip-hostname.ps1"
 
  - name: create custom autounattend iso image
    #command: mkisofs -r -N -allow-leading-dots -d -J -T -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -V "{{ inventory_hostname_short }}" -boot-load-size 4 -boot-info-table -o build/{{ inventory_hostname }}.iso {{ tempdir.stdout }}
    command: genisoimage -o build/{{ inventory_hostname }}.iso -J -R -v -T -V 'autounattend.xml' {{ tempdir.stdout }}
    delegate_to: localhost

  - name: upload Windows ISO 
    when: iso_exists.state == "absent"
    vsphere_copy:
      hostname: "{{ vsphere_hostname }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      datacenter: "{{ vsphere_datacenter }}"
      datastore: "{{ vsphere_iso_datastore }}"
      src: build/{{ iso_image }}
      path: "{{ vsphere_iso_directory }}/{{  iso_image }}"
      timeout: 360
      validate_certs: False
 
  - name: upload custom ISO for autounattend.xml
    vsphere_copy:
      hostname: "{{ vsphere_hostname }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      datacenter: "{{ vsphere_datacenter }}"
      datastore: "{{ vsphere_iso_datastore }}"
      src: build/{{ inventory_hostname }}.iso
      path: "{{ vsphere_iso_directory }}/{{ inventory_hostname }}.iso"
      timeout: 360
      validate_certs: False

  - name: cleanup temp directories
    file:
      path: "{{ tempdir.stdout }}"
      state: absent
 
  - name: cleanup custom iso from build directory
    file:
      path: build/{{ inventory_hostname }}.iso
      state: absent
 
  - name: create vm
    vmware_guest:
      validate_certs: False
      hostname: "{{ vsphere_hostname }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      datacenter: "{{ vsphere_datacenter }}"
      esxi_hostname: "{{ esxi_hostname }}"
      folder: /
      name: "{{ inventory_hostname }}"
      guest_id: windows9_64Guest
      state: poweredon
      disk:
        - size_gb: "{{ disk_gb }}" 
          controller_type: lsilogicsas
          controller_number: 0
          unit_number: 0
          type: thin
          datastore: "{{ vsphere_datastore }}"
      networks:
        - name: "{{ vm_network }}"
          device_type: e1000e
      hardware:
        memory_mb: "{{ ram_mb }}"
        num_cpus: "{{ cpu_count }}"
        boot_firmware: efi
        scsi: lsilogicsas
      cdrom:
        - controller_number: 1
          controller_type: ide
          unit_number: 0
          type: iso
          iso_path: "[{{ vsphere_iso_datastore }}] /{{ vsphere_iso_directory }}/{{ iso_image }}"
        - controller_number: 1
          controller_type: ide
          unit_number: 1
          type: iso
          iso_path: "[{{ vsphere_iso_datastore }}] /{{ vsphere_iso_directory }}/{{ inventory_hostname }}.iso"

  - name: Add USB 3.0 controllers for virtual machine
    community.vmware.vmware_guest_controller:
      validate_certs: False
      hostname: "{{ vsphere_hostname }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      datacenter: "{{ vsphere_datacenter }}"
      name: "{{ inventory_hostname }}"
      controllers:
        - state: present
          type: usb3
    delegate_to: localhost
    register: disk_controller_facts

  - name: delete custom iso image from datastore
    when: False 
    vsphere_copy:
      validate_certs: False
      hostname: '{{ vsphere_hostname }}'
      username: '{{ vsphere_username }}'
      password: '{{ vsphere_password }}'
      datacenter: "{{ vsphere_datacenter }}"
      datastore: "{{ vsphere_datastore }}"
      path: "{{ vsphere_iso_directory }}/{{ inventory_hostname }}.iso"
      state: absent
    delegate_to: localhost
