- hosts: all

  vars:
    github_repo: "https://github.com/user/repo/"
    tempdir: /root/ansible/src/
    capture_interface: ens224

  tasks:
  - name: install packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
        - suricata
        - netsniff-ng
        - bro
        - tcpdump

  - name: configuration for netsniff-ng
    copy:
      dest: /etc/sysconfig/netsniff-ng
      content: |
        CAPTURE_INTERFACE={{ capture_interface }}
        USER=72
        GROUP=72
        INTERVAL=60min
        DATA_DIR=/mnt/data
        DATA_EXPIRE=600


  - name: service for netsniff-ng
    copy:
      dest: /etc/systemd/
      src: files/netsniff-ng.service

  - name: cron script for netsniff-ng pcap cleanup
    copy:
      dest: /etc/cron.hourly/
      src: files/netsniff-ng.cleanup.sh

  - name: create /mnt/data and set permissions
    file:
      path: /mnt/data
      state: directory
      mode: '0755'
      owner: 72
      group: 72

  - name: Set capture interface in suricata config
    replace:
      path: /etc/sysconfig/suricata
      regexp: 'eth0'
      replace: "{{ capture_interface }}"
